-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_baby_bear]: type definitions
import Aeneas
import CoreModels
import P3BabyBear.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace p3_baby_bear

/-- [p3_baby_bear::baby_bear::BabyBearParameters]
    Source: 'baby-bear/src/baby_bear.rs', lines 12:0-12:30
    Visibility: public -/
@[reducible]
def baby_bear.BabyBearParameters := Unit

/-- [p3_baby_bear::mds::MDSBabyBearData]
    Source: 'baby-bear/src/mds.rs', lines 13:0-13:27
    Visibility: public -/
@[reducible]
def mds.MDSBabyBearData := Unit

/-- [p3_baby_bear::poseidon1::BabyBearPoseidonParameters]
    Source: 'baby-bear/src/poseidon1.rs', lines 94:0-94:38
    Visibility: public -/
@[reducible]
def poseidon1.BabyBearPoseidonParameters := Unit

/-- [p3_baby_bear::poseidon2::BabyBearInternalLayerParameters]
    Source: 'baby-bear/src/poseidon2.rs', lines 393:0-393:43
    Visibility: public -/
@[reducible]
def poseidon2.BabyBearInternalLayerParameters := Unit

end p3_baby_bear
