-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_mds]: function definitions
import Aeneas
import CoreModels
import P3Mds.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace p3_mds

/-- [p3_mds::util::first_row_to_first_col]: loop body 0:
    Source: 'mds/src/util.rs', lines 56:4-60:5
    Visibility: public -/
@[rust_loop_body]
def util.first_row_to_first_col_loop.body
  {T : Type} {N : Std.Usize} (v : Array T N) (output : Array T N)
  (i : Std.Usize) :
  RustM (ControlFlow ((Array T N) × Std.Usize) (Array T N))
  := do
  if i < N
  then
    let i1 ← N - i
    let t ← Array.index_usize v i1
    let a ← Array.update output i t
    let i2 ← i + 1#usize
    ok (cont (a, i2))
  else ok (done output)

/-- [p3_mds::util::first_row_to_first_col]: loop 0:
    Source: 'mds/src/util.rs', lines 56:4-60:5
    Visibility: public -/
@[rust_loop]
def util.first_row_to_first_col_loop
  {T : Type} {N : Std.Usize} (v : Array T N) (output : Array T N)
  (i : Std.Usize) :
  RustM (Array T N)
  := do
  loop
    (fun (output1, i1) => util.first_row_to_first_col_loop.body v output1 i1)
    (output, i)

/-- [p3_mds::util::first_row_to_first_col]:
    Source: 'mds/src/util.rs', lines 52:0-62:1
    Visibility: public -/
@[reducible]
def util.first_row_to_first_col
  {T : Type} {N : Std.Usize} (coremarkerCopyInst : core.marker.Copy T)
  (v : Array T N) :
  RustM (Array T N)
  := do
  util.first_row_to_first_col_loop v v 1#usize

end p3_mds
