-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_monty_31]: function definitions
import Aeneas
import CoreModels
import P3Monty31.Extraction.Types
import P3Monty31.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace p3_monty_31

/-- [p3_monty_31::data_traits::MontyParameters::MONTY_MASK]
    Source: 'monty-31/src/data_traits.rs', lines 23:4-23:68
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.MontyParameters.MONTY_MASK.default {Self : Type}
  (MontyParametersInst : data_traits.MontyParameters Self)
  : RustM Std.U32 := do
  let i ← MontyParametersInst.MONTY_BITS
  let i1 ← 1#u64 <<< i
  let i2 ← i1 - 1#u64
  ok (UScalar.cast .U32 i2)

/-- [p3_monty_31::data_traits::BarrettParameters::N]
    Source: 'monty-31/src/data_traits.rs', lines 53:4-53:24
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.BarrettParameters.N.default (Self : Type) : Std.Usize :=
  40#usize

/-- [p3_monty_31::data_traits::BarrettParameters::PRIME_I128]
    Source: 'monty-31/src/data_traits.rs', lines 54:4-54:49
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.BarrettParameters.PRIME_I128.default {Self : Type}
  (BarrettParametersInst : data_traits.BarrettParameters Self)
  : RustM Std.I128 := do
  let i ← BarrettParametersInst.MontyParametersInst.PRIME
  ok (UScalar.hcast .I128 i)

/-- [p3_monty_31::data_traits::BarrettParameters::PSEUDO_INV]
    Source: 'monty-31/src/data_traits.rs', lines 55:4-55:84
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.BarrettParameters.PSEUDO_INV.default {Self : Type}
  (BarrettParametersInst : data_traits.BarrettParameters Self)
  : RustM Std.I64 := do
  let i ← BarrettParametersInst.N
  let i1 ← 2#usize * i
  let i2 ← 1#i128 <<< i1
  let i3 ← BarrettParametersInst.PRIME_I128
  let i4 ← i2 / i3
  ok (IScalar.cast .I64 i4)

/-- [p3_monty_31::data_traits::BarrettParameters::MASK]
    Source: 'monty-31/src/data_traits.rs', lines 56:4-56:39
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.BarrettParameters.MASK.default (Self : Type)
  : RustM Std.I64 := do
  let i ← 1#i64 <<< 10#i32
  let i1 ← i - 1#i64
  ok (~~~ i1)

/-- [p3_monty_31::utils::to_monty]:
    Source: 'monty-31/src/utils.rs', lines 7:0-9:1 -/
def utils.to_monty
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (x : Std.U32) :
  RustM Std.U32
  := do
  let i ← lift (UScalar.cast .U64 x)
  let i1 ← data_traitsMontyParametersInst.MONTY_BITS
  let i2 ← i <<< i1
  let i3 ← data_traitsMontyParametersInst.PRIME
  let i4 ← lift (UScalar.cast .U64 i3)
  let i5 ← i2 % i4
  ok (UScalar.cast .U32 i5)

/-- [p3_monty_31::monty_31::{p3_monty_31::monty_31::MontyField31<MP>[TraitClause0]}::new]:
    Source: 'monty-31/src/monty_31.rs', lines 51:4-65:5
    Visibility: public -/
def monty_31.MontyField31.new
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (value : Std.U32) :
  RustM (monty_31.MontyField31 MP)
  := do
  let i ← data_traitsMontyParametersInst.PRIME
  let i1 ← i % 2#u32
  massert (i1 = 1#u32)
  let i2 ← 1#u32 <<< 31#i32
  massert (i < i2)
  let i3 ← data_traitsMontyParametersInst.MONTY_BITS
  massert (i3 = 32#u32)
  let i4 ← data_traitsMontyParametersInst.MONTY_MU
  let i5 ← core.num.U32.wrapping_mul i i4
  massert (i5 = 1#u32)
  let i6 ← utils.to_monty data_traitsMontyParametersInst value
  ok { value := i6, _phantom := () }

/-- [p3_monty_31::data_traits::FieldParameters::MONTY_ZERO]
    Source: 'monty-31/src/data_traits.rs', lines 62:4-62:64
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.MONTY_ZERO.default {Self : Type}
  (FieldParametersInst : data_traits.FieldParameters Self)
  : RustM (monty_31.MontyField31 Self) :=
  monty_31.MontyField31.new
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst 0#u32

/-- [p3_monty_31::data_traits::FieldParameters::MONTY_ONE]
    Source: 'monty-31/src/data_traits.rs', lines 63:4-63:63
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.MONTY_ONE.default {Self : Type}
  (FieldParametersInst : data_traits.FieldParameters Self)
  : RustM (monty_31.MontyField31 Self) :=
  monty_31.MontyField31.new
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst 1#u32

/-- [p3_monty_31::data_traits::FieldParameters::MONTY_TWO]
    Source: 'monty-31/src/data_traits.rs', lines 64:4-64:63
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.MONTY_TWO.default {Self : Type}
  (FieldParametersInst : data_traits.FieldParameters Self)
  : RustM (monty_31.MontyField31 Self) :=
  monty_31.MontyField31.new
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst 2#u32

/-- [p3_monty_31::data_traits::FieldParameters::MONTY_NEG_ONE]
    Source: 'monty-31/src/data_traits.rs', lines 65:4-65:81
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.MONTY_NEG_ONE.default {Self : Type}
  (FieldParametersInst : data_traits.FieldParameters Self)
  : RustM (monty_31.MontyField31 Self) := do
  let i ←
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst.PRIME
  let i1 ← i - 1#u32
  monty_31.MontyField31.new
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst i1

/-- [p3_monty_31::data_traits::FieldParameters::HALF_P_PLUS_1]
    Source: 'monty-31/src/data_traits.rs', lines 70:4-70:54
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.HALF_P_PLUS_1.default {Self : Type}
  (FieldParametersInst : data_traits.FieldParameters Self)
  : RustM Std.U32 := do
  let i ←
    FieldParametersInst.PackedMontyParametersInst.MontyParametersInst.PRIME
  let i1 ← i + 1#u32
  i1 >>> 1#i32

/-- [p3_monty_31::data_traits::FieldParameters::BENEFITS_FROM_LOCKSTEP_EVALUATION]
    Source: 'monty-31/src/data_traits.rs', lines 77:4-77:58
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.FieldParameters.BENEFITS_FROM_LOCKSTEP_EVALUATION.default (Self
  : Type) : Bool :=
  false

/-- [p3_monty_31::data_traits::TwoAdicData::ODD_FACTOR]
    Source: 'monty-31/src/data_traits.rs', lines 93:4-93:70
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def data_traits.TwoAdicData.ODD_FACTOR.default {Self : Type} {Clause0_ArrayLike
  : Type} (TwoAdicDataInst : data_traits.TwoAdicData Self Clause0_ArrayLike)
  : RustM Std.I32 := do
  let i ← TwoAdicDataInst.MontyParametersInst.PRIME
  let i1 ← TwoAdicDataInst.TWO_ADICITY
  let i2 ← i >>> i1
  ok (UScalar.hcast .I32 i2)

/-- [p3_monty_31::monty_31::{impl core::clone::Clone for p3_monty_31::monty_31::MontyField31<MP>}::clone]:
    Source: 'monty-31/src/monty_31.rs', lines 34:9-34:14
    Visibility: public -/
def monty_31.MontyField31.Insts.CoreCloneClone.clone
  {MP : Type} (corecloneCloneInst : core.clone.Clone MP)
  (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (self : monty_31.MontyField31 MP) :
  RustM (monty_31.MontyField31 MP)
  := do
  let i ← core.U32.Insts.CoreCloneClone.clone self.value
  let pd ← core.marker.PhantomData.Insts.CoreCloneClone.clone self._phantom
  ok { value := i, _phantom := pd }

/-- Trait implementation: [p3_monty_31::monty_31::{impl core::clone::Clone for p3_monty_31::monty_31::MontyField31<MP>}]
    Source: 'monty-31/src/monty_31.rs', lines 34:9-34:14 -/
@[reducible]
def monty_31.MontyField31.Insts.CoreCloneClone {MP : Type} (corecloneCloneInst
  : core.clone.Clone MP) (data_traitsMontyParametersInst :
  data_traits.MontyParameters MP) : core.clone.Clone (monty_31.MontyField31 MP)
  := {
  clone := monty_31.MontyField31.Insts.CoreCloneClone.clone corecloneCloneInst
    data_traitsMontyParametersInst
  -- PATCHED: default method, body of `core.clone.Clone.clone_from.default`
  clone_from := fun _ source => (monty_31.MontyField31.Insts.CoreCloneClone.clone corecloneCloneInst data_traitsMontyParametersInst) source
}

/-- [p3_monty_31::poseidon1::PartialRoundBaseParameters::USE_TEXTBOOK]
    Source: 'monty-31/src/poseidon1.rs', lines 34:4-34:37
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def poseidon1.PartialRoundBaseParameters.USE_TEXTBOOK.default (Self : Type) (MP
  : Type) (WIDTH : Std.Usize) : Bool :=
  false

/-- [p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::{impl core::ops::function::FnMut<(&'_ R,), R> for p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::closure<Self, MP, R, WIDTH>[TraitClause0, TraitClause1]}::call_mut]:
    Source: 'monty-31/src/poseidon2.rs', lines 29:48-29:59 -/
def
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnMutTupleSharedRR.call_mut
  {Self : Type} {MP : Type} {R : Type} {WIDTH : Std.Usize}
  (InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
  MP WIDTH) (p3_fieldfieldPrimeCharacteristicRingInst :
  p3_field.field.PrimeCharacteristicRing R)
  (c :
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
  InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst)
  (tupled_args : R) :
  RustM (R ×
    (poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
    InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst))
  := do
  let t ← p3_fieldfieldPrimeCharacteristicRingInst.dupDupInst.dup tupled_args
  ok (t, c)

/-- [p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::{impl core::ops::function::FnOnce<(&'_ R,), R> for p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::closure<Self, MP, R, WIDTH>[TraitClause0, TraitClause1]}::call_once]:
    Source: 'monty-31/src/poseidon2.rs', lines 29:48-29:59 -/
def
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnOnceTupleSharedRR.call_once
  {Self : Type} {MP : Type} {R : Type} {WIDTH : Std.Usize}
  (InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
  MP WIDTH) (p3_fieldfieldPrimeCharacteristicRingInst :
  p3_field.field.PrimeCharacteristicRing R)
  (c :
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
  InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst)
  (t : R) :
  RustM R
  := do
  let (t1, _) ←
    poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnMutTupleSharedRR.call_mut
      InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst
      c t
  ok t1

/-- Trait implementation: [p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::{impl core::ops::function::FnOnce<(&'_ R,), R> for p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::closure<Self, MP, R, WIDTH>[TraitClause0, TraitClause1]}]
    Source: 'monty-31/src/poseidon2.rs', lines 29:48-29:59 -/
@[reducible]
def
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnOnceTupleSharedRR
  {Self : Type} {MP : Type} {R : Type} {WIDTH : Std.Usize}
  (InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
  MP WIDTH) (p3_fieldfieldPrimeCharacteristicRingInst :
  p3_field.field.PrimeCharacteristicRing R) : core.ops.function.FnOnce
  (poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
  InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst) R R
  := {
  call_once :=
    poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnOnceTupleSharedRR.call_once
    InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst
}

/-- Trait implementation: [p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::{impl core::ops::function::FnMut<(&'_ R,), R> for p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::closure<Self, MP, R, WIDTH>[TraitClause0, TraitClause1]}]
    Source: 'monty-31/src/poseidon2.rs', lines 29:48-29:59 -/
@[reducible]
def
  poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnMutTupleSharedRR
  {Self : Type} {MP : Type} {R : Type} {WIDTH : Std.Usize}
  (InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
  MP WIDTH) (p3_fieldfieldPrimeCharacteristicRingInst :
  p3_field.field.PrimeCharacteristicRing R) : core.ops.function.FnMut
  (poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
  InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst) R R
  := {
  FnOnceInst :=
    poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnOnceTupleSharedRR
    InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst
  call_mut :=
    poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure.Insts.CoreOpsFunctionFnMutTupleSharedRR.call_mut
    InternalLayerBaseParametersInst p3_fieldfieldPrimeCharacteristicRingInst
}

/-- [p3_monty_31::utils::monty_reduce]:
    Source: 'monty-31/src/utils.rs', lines 105:0-125:1 -/
def utils.monty_reduce
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (x : Std.U64) :
  RustM Std.U32
  := do
  let i ← data_traitsMontyParametersInst.MONTY_MU
  let i1 ← lift (UScalar.cast .U64 i)
  let i2 ← core.num.U64.wrapping_mul x i1
  let i3 ← data_traitsMontyParametersInst.MONTY_MASK
  let i4 ← lift (UScalar.cast .U64 i3)
  let t ← lift (i2 &&& i4)
  let i5 ← data_traitsMontyParametersInst.PRIME
  let i6 ← lift (UScalar.cast .U64 i5)
  let u ← t * i6
  let (x_sub_u, over) ← core.num.U64.overflowing_sub x u
  let i7 ← data_traitsMontyParametersInst.MONTY_BITS
  let i8 ← x_sub_u >>> i7
  let x_sub_u_hi ← lift (UScalar.cast .U32 i8)
  let corr ← if over
               then ok i5
               else ok 0#u32
  core.num.U32.wrapping_add x_sub_u_hi corr

/-- [p3_monty_31::utils::from_monty]:
    Source: 'monty-31/src/utils.rs', lines 50:0-52:1 -/
def utils.from_monty
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (x : Std.U32) :
  RustM Std.U32
  := do
  let i ← lift (UScalar.cast .U64 x)
  utils.monty_reduce data_traitsMontyParametersInst i

/-- [p3_monty_31::utils::add]:
    Source: 'monty-31/src/utils.rs', lines 63:0-70:1 -/
def utils.add
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (lhs : Std.U32) (rhs : Std.U32) :
  RustM Std.U32
  := do
  let sum ← lhs + rhs
  let i ← data_traitsMontyParametersInst.PRIME
  let (corr_sum, over) ← core.num.U32.overflowing_sub sum i
  if over
  then ok sum
  else ok corr_sum

/-- [p3_monty_31::utils::sub]:
    Source: 'monty-31/src/utils.rs', lines 81:0-86:1 -/
def utils.sub
  {MP : Type} (data_traitsMontyParametersInst : data_traits.MontyParameters MP)
  (lhs : Std.U32) (rhs : Std.U32) :
  RustM Std.U32
  := do
  let (diff, over) ← core.num.U32.overflowing_sub lhs rhs
  let corr ← if over
               then data_traitsMontyParametersInst.PRIME
               else ok 0#u32
  core.num.U32.wrapping_add diff corr

/-- [p3_monty_31::utils::halve_u32]:
    Source: 'monty-31/src/utils.rs', lines 92:0-97:1 -/
def utils.halve_u32
  {FP : Type} (data_traitsFieldParametersInst : data_traits.FieldParameters FP)
  (input : Std.U32) :
  RustM Std.U32
  := do
  let shr ← input >>> 1#i32
  let lo_bit ← lift (input &&& 1#u32)
  let i ← data_traitsFieldParametersInst.HALF_P_PLUS_1
  let shr_corr ← shr + i
  if lo_bit = 0#u32
  then ok shr
  else ok shr_corr

end p3_monty_31
