-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [p3_monty_31]: type definitions
import Aeneas
import CoreModels
import P3Monty31.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace p3_monty_31

/-- Trait declaration: [p3_monty_31::data_traits::MontyParameters]
    Source: 'monty-31/src/data_traits.rs', lines 10:0-24:1
    Visibility: public -/
structure data_traits.MontyParameters (Self : Type) where
  PRIME : RustM Std.U32
  MONTY_BITS : RustM Std.U32
  MONTY_MU : RustM Std.U32
  MONTY_MASK : RustM Std.U32
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  corefmtDebugInst : core.fmt.Debug Self
  corecmpEqInst : core.cmp.Eq Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corehashHashInst : core.hash.Hash Self

/-- Trait declaration: [p3_monty_31::data_traits::PackedMontyParameters]
    Source: 'monty-31/src/data_traits.rs', lines 49:0-49:51
    Visibility: public -/
structure data_traits.PackedMontyParameters (Self : Type) where
  MontyParametersInst : data_traits.MontyParameters Self

/-- Trait declaration: [p3_monty_31::data_traits::BarrettParameters]
    Source: 'monty-31/src/data_traits.rs', lines 52:0-57:1
    Visibility: public -/
structure data_traits.BarrettParameters (Self : Type) where
  N : RustM Std.Usize
  PRIME_I128 : RustM Std.I128
  PSEUDO_INV : RustM Std.I64
  MASK : RustM Std.I64
  MontyParametersInst : data_traits.MontyParameters Self

/-- [p3_monty_31::monty_31::MontyField31]
    Source: 'monty-31/src/monty_31.rs', lines 37:0-44:1
    Visibility: public -/
structure monty_31.MontyField31 (MP : Type) where
  value : Std.U32
  _phantom : core.marker.PhantomData MP

/-- Trait declaration: [p3_monty_31::data_traits::FieldParameters]
    Source: 'monty-31/src/data_traits.rs', lines 60:0-78:1
    Visibility: public -/
structure data_traits.FieldParameters (Self : Type) where
  MONTY_ZERO : RustM (monty_31.MontyField31 Self)
  MONTY_ONE : RustM (monty_31.MontyField31 Self)
  MONTY_TWO : RustM (monty_31.MontyField31 Self)
  MONTY_NEG_ONE : RustM (monty_31.MontyField31 Self)
  MONTY_GEN : RustM (monty_31.MontyField31 Self)
  HALF_P_PLUS_1 : RustM Std.U32
  BENEFITS_FROM_LOCKSTEP_EVALUATION : RustM Bool
  PackedMontyParametersInst : data_traits.PackedMontyParameters Self

/-- Trait declaration: [p3_monty_31::data_traits::RelativelyPrimePower]
    Source: 'monty-31/src/data_traits.rs', lines 81:0-85:1
    Visibility: public -/
structure data_traits.RelativelyPrimePower (Self : Type) (D : Std.U64) where
  exp_root_d : forall {R : Type} (p3_fieldfieldPrimeCharacteristicRingInst :
    p3_field.field.PrimeCharacteristicRing R), R → RustM R

/-- Trait declaration: [p3_monty_31::data_traits::TwoAdicData]
    Source: 'monty-31/src/data_traits.rs', lines 88:0-119:1
    Visibility: public -/
structure data_traits.TwoAdicData (Self : Type) (Self_ArrayLike : Type) where
  TWO_ADICITY : RustM Std.Usize
  ODD_FACTOR : RustM Std.I32
  TWO_ADIC_GENERATORS : RustM Self_ArrayLike
  ROOTS_8 : RustM Self_ArrayLike
  INV_ROOTS_8 : RustM Self_ArrayLike
  ROOTS_16 : RustM Self_ArrayLike
  INV_ROOTS_16 : RustM Self_ArrayLike
  MontyParametersInst : data_traits.MontyParameters Self
  coreconvertAsRefSelf_ArrayLikeSliceMontyField31Inst : core.convert.AsRef
    Self_ArrayLike (Slice (monty_31.MontyField31 Self))

/-- Trait declaration: [p3_monty_31::data_traits::BinomialExtensionData]
    Source: 'monty-31/src/data_traits.rs', lines 123:0-149:1
    Visibility: public -/
structure data_traits.BinomialExtensionData (Self : Type) (Self_ArrayLike :
  Type) (DEG : Std.Usize) where
  W : RustM (monty_31.MontyField31 Self)
  DTH_ROOT : RustM (monty_31.MontyField31 Self)
  EXT_GENERATOR : RustM (Array (monty_31.MontyField31 Self) DEG)
  EXT_TWO_ADICITY : RustM Std.Usize
  TWO_ADIC_EXTENSION_GENERATORS : RustM Self_ArrayLike
  MontyParametersInst : data_traits.MontyParameters Self
  coreconvertAsRefSelf_ArrayLikeSliceArrayMontyField31DEGInst :
    core.convert.AsRef Self_ArrayLike (Slice (Array (monty_31.MontyField31
    Self) DEG))

/-- Trait declaration: [p3_monty_31::mds::MDSUtils]
    Source: 'monty-31/src/mds.rs', lines 11:0-18:1
    Visibility: public -/
structure mds.MDSUtils (Self : Type) where
  MATRIX_CIRC_MDS_8_COL : RustM (Array Std.I64 8#usize)
  MATRIX_CIRC_MDS_12_COL : RustM (Array Std.I64 12#usize)
  MATRIX_CIRC_MDS_16_COL : RustM (Array Std.I64 16#usize)
  MATRIX_CIRC_MDS_24_COL : RustM (Array Std.I64 24#usize)
  MATRIX_CIRC_MDS_32_COL : RustM (Array Std.I64 32#usize)
  MATRIX_CIRC_MDS_64_COL : RustM (Array Std.I64 64#usize)
  corecloneCloneInst : core.clone.Clone Self

/-- Trait declaration: [p3_monty_31::poseidon1::PartialRoundBaseParameters]
    Source: 'monty-31/src/poseidon1.rs', lines 27:0-38:1
    Visibility: public -/
structure poseidon1.PartialRoundBaseParameters (Self : Type) (MP : Type) (WIDTH
  : Std.Usize) where
  USE_TEXTBOOK : RustM Bool
  corecloneCloneInst : core.clone.Clone Self
  data_traitsMontyParametersInst : data_traits.MontyParameters MP

/-- Trait declaration: [p3_monty_31::poseidon1::PartialRoundParameters]
    Source: 'monty-31/src/poseidon1.rs', lines 68:0-71:1
    Visibility: public -/
structure poseidon1.PartialRoundParameters (Self : Type) (FP : Type) (WIDTH :
  Std.Usize) where
  PartialRoundBaseParametersInst : poseidon1.PartialRoundBaseParameters Self FP
    WIDTH
  data_traitsFieldParametersInst : data_traits.FieldParameters FP

/-- Trait declaration: [p3_monty_31::poseidon2::InternalLayerBaseParameters]
    Source: 'monty-31/src/poseidon2.rs', lines 18:0-34:1
    Visibility: public -/
structure poseidon2.InternalLayerBaseParameters (Self : Type) (MP : Type)
  (WIDTH : Std.Usize) where
  corecloneCloneInst : core.clone.Clone Self
  data_traitsMontyParametersInst : data_traits.MontyParameters MP
  internal_layer_mat_mul : forall {R : Type}
    (p3_fieldfieldPrimeCharacteristicRingInst :
    p3_field.field.PrimeCharacteristicRing R), Array R WIDTH → R → RustM
    (Array R WIDTH)

/-- [p3_monty_31::poseidon2::InternalLayerBaseParameters::generic_internal_linear_layer::closure]
    Source: 'monty-31/src/poseidon2.rs', lines 29:48-29:59 -/
@[reducible]
def poseidon2.InternalLayerBaseParameters.generic_internal_linear_layer.closure
  {Self : Type} {MP : Type} {R : Type} {WIDTH : Std.Usize}
  (InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
  MP WIDTH) (p3_fieldfieldPrimeCharacteristicRingInst :
  p3_field.field.PrimeCharacteristicRing R) :=
Unit

/-- Trait declaration: [p3_monty_31::poseidon2::InternalLayerParameters]
    Source: 'monty-31/src/poseidon2.rs', lines 64:0-67:1
    Visibility: public -/
structure poseidon2.InternalLayerParameters (Self : Type) (FP : Type) (WIDTH :
  Std.Usize) where
  InternalLayerBaseParametersInst : poseidon2.InternalLayerBaseParameters Self
    FP WIDTH
  data_traitsFieldParametersInst : data_traits.FieldParameters FP

end p3_monty_31
